version: '3.3'

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8345:80

  frontend:
    build:
      context: ./client/acc-telemetry-tracker
      dockerfile: Dockerfile
    depends_on:
      - api
    restart: always
    environment:
      API_URL:
      DISCORD_CLIENT_ID: 12345
  
  database:
    build:
      context: ./datastore
      dockerfile: Dockerfile
    volumes:
      - /some/database/file/path:/var/lib/mysql
      #- db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: super-secure-root-password
      MYSQL_DATABASE: acc_telemetry_tracker
      MYSQL_USER: acc_user
      MYSQL_PASSWORD: acc_password

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - database
    restart: always
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: acc_telemetry_tracker
      DATABASE_USER: acc_user
      DATABASE_PASSWORD: acc_password
      DISCORD_CLIENT_ID: 
      DISCORD_CLIENT_SECRET: 
      DISCORD_GUILD_ID: 98765
      STORAGE_PATH: /motec
      FRONTEND_URL: http://full-front-end-url
      ADMIN_USERS: 12345,56789
    ports:
      - 8346:80
    volumes:
      - /some/motec/path:/motec
      # next one is optional
      - /some/log/path:/app/logs


# you can use this type of mount if you want instead
#volumes:
#  db_data: