<?xml version="1.0"?>
<LDXFile Locale="English_Canada.1252" DefaultLocale="C" Version="1.6">
 <Layers>
  <Layer>
   <MarkerBlock>
    <MarkerGroup Name="Beacons" Index="0">
     <Marker Version="100" ClassName="BCN" Name="0, id=99" Flags="13" Time="6.68170000000000000e+07"/>
     <Marker Version="100" ClassName="BCN" Name="1, id=99" Flags="13" Time="1.76346000000000000e+08"/>
     <Marker Version="100" ClassName="BCN" Name="2, id=99" Flags="13" Time="2.78975000000000000e+08"/>
     <Marker Version="100" ClassName="BCN" Name="3, id=99" Flags="13" Time="3.81224000000000000e+08"/>
     <Marker Version="100" ClassName="BCN" Name="4, id=99" Flags="13" Time="4.82693000000000000e+08"/>
     <Marker Version="100" ClassName="BCN" Name="5, id=99" Flags="13" Time="6.32507000000000000e+08"/>
     <Marker Version="100" ClassName="BCN" Name="6, id=99" Flags="13" Time="7.41244000000000000e+08"/>
     <Marker Version="100" ClassName="BCN" Name="7, id=99" Flags="13" Time="8.43241000000000000e+08"/>
     <Marker Version="100" ClassName="BCN" Name="8, id=99" Flags="13" Time="9.45140000000000000e+08"/>
     <Marker Version="100" ClassName="BCN" Name="9, id=99" Flags="13" Time="1.04695000000000000e+09"/>
     <Marker Version="100" ClassName="BCN" Name="10, id=99" Flags="13" Time="1.08355000000000000e+09"/>
     <Marker Version="100" ClassName="BCN" Name="11, id=99" Flags="13" Time="1.19131000000000000e+09"/>
     <Marker Version="100" ClassName="BCN" Name="12, id=99" Flags="13" Time="1.29300000000000000e+09"/>
     <Marker Version="100" ClassName="BCN" Name="13, id=99" Flags="13" Time="1.39469000000000000e+09"/>
     <Marker Version="100" ClassName="BCN" Name="14, id=99" Flags="13" Time="1.49638000000000000e+09"/>
     <Marker Version="100" ClassName="BCN" Name="15, id=99" Flags="13" Time="1.59773000000000000e+09"/>
    </MarkerGroup>
   </MarkerBlock>
   <RangeBlock/>
  </Layer>
  <Details>
   <String Id="Total Laps" Value="17"/>
   <String Id="Fastest Time" Value="0:36.600"/>
   <String Id="Fastest Lap" Value="10"/>
  </Details>
 </Layers>
</LDXFile>
