// <auto-generated />
using System;
using AccTelemetryTracker.Datastore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccTelemetryTracker.Datastore.Migrations
{
    [DbContext(typeof(AccTelemetryTrackerContext))]
    partial class AccTelemetryTrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("AccTelemetryTracker.Datastore.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("AccTelemetryTracker.Datastore.Models.MotecFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateInserted")
                        .HasColumnType("TEXT");

                    b.Property<double>("FastestLap")
                        .HasColumnType("REAL");

                    b.Property<string>("FileLocation")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfLaps")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("TrackId");

                    b.ToTable("MotecFiles", (string)null);
                });

            modelBuilder.Entity("AccTelemetryTracker.Datastore.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tracks", (string)null);
                });

            modelBuilder.Entity("AccTelemetryTracker.Datastore.Models.MotecFile", b =>
                {
                    b.HasOne("AccTelemetryTracker.Datastore.Models.Car", "Car")
                        .WithMany("MotecFiles")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccTelemetryTracker.Datastore.Models.Track", "Track")
                        .WithMany("MotecFiles")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("AccTelemetryTracker.Datastore.Models.Car", b =>
                {
                    b.Navigation("MotecFiles");
                });

            modelBuilder.Entity("AccTelemetryTracker.Datastore.Models.Track", b =>
                {
                    b.Navigation("MotecFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
